const items = [
  {
    kategori: "all",
    items: [
      {
        id: 1,
        nama: "Lemari Kayu Solid",
        harga: 1200000,
        deskripsi: "Lemari kayu solid dengan desain modern dan elegan.",
        image: require("../assets/lemari_laci.jpg"),
        kategori: "lemari",
      },
      {
        id: 2,
        nama: "Meja Makan Minimalis",
        harga: 800000,
        deskripsi: "Meja makan minimalis dengan bahan berkualitas tinggi.",
        image: require("../assets/meja_kursi_makan_set_4_kayu.jpg"),
        kategori: "meja",
      },
      {
        id: 3,
        nama: "Kursi Sofa Empuk",
        harga: 600000,
        deskripsi: "Kursi sofa empuk yang nyaman untuk duduk.",
        image: require("../assets/kursi_putih.jpg"),
        kategori: "kursi",
      },
      {
        id: 4,
        nama: "Lemari Pakaian Kayu",
        harga: 1500000,
        deskripsi: "Lemari pakaian kayu dengan ruang penyimpanan yang luas.",
        image: require("../assets/lemari_pakaian_2_pintu_cermin.jpg"),
        kategori: "lemari",
      },
      {
        id: 5,
        nama: "Meja Kerja Modern",
        harga: 1000000,
        deskripsi: "Meja kerja modern dengan desain minimalis.",
        image: require("../assets/meja_kursi_makan_set_2.jpg"),
        kategori: "meja",
      },
      {
        id: 6,
        nama: "Kursi Santai Bulat",
        harga: 500000,
        deskripsi: "Kursi santai bulat yang cocok untuk ruang tamu.",
        image: require("../assets/kursi_hitam.jpg"),
        kategori: "kursi",
      },
      {
        id: 7,
        nama: "Lemari TV Kayu Jati",
        harga: 1800000,
        deskripsi: "Lemari TV kayu jati dengan tampilan klasik.",
        image: require("../assets/lemari_laci.jpg"),
        kategori: "lemari",
      },
      {
        id: 8,
        nama: "Meja Belajar Anak",
        harga: 600000,
        deskripsi: "Meja belajar anak dengan warna cerah dan menyenangkan.",
        image: require("../assets/lemari_laci.jpg"),
        kategori: "meja",
      },
      {
        id: 9,
        nama: "Kursi Lipat Portable",
        harga: 350000,
        deskripsi: "Kursi lipat portabel yang mudah dibawa ke mana saja.",
        image: require("../assets/lemari_laci.jpg"),
        kategori: "kursi",
      },
      {
        id: 10,
        nama: "Lemari Buku Minimalis",
        harga: 900000,
        deskripsi: "Lemari buku minimalis dengan rak penyimpanan yang praktis.",
        image: require("../assets/lemari_laci.jpg"),
        kategori: "lemari",
      },
    ],
  },
  {
    kategori: "lemari",
    items: [
      {
        id: 1,
        nama: "Lemari Kayu Solid",
        harga: 1200000,
        deskripsi: "Lemari kayu solid dengan desain modern dan elegan.",
        image: require("../assets/lemari_laci.jpg"),
        kategori: "lemari",
      },
      {
        id: 4,
        nama: "Lemari Pakaian Kayu",
        harga: 1500000,
        deskripsi: "Lemari pakaian kayu dengan ruang penyimpanan yang luas.",
        image: require("../assets/lemari_laci.jpg"),
        kategori: "lemari",
      },
      {
        id: 7,
        nama: "Lemari TV Kayu Jati",
        harga: 1800000,
        deskripsi: "Lemari TV kayu jati dengan tampilan klasik.",
        image: require("../assets/lemari_laci.jpg"),
        kategori: "lemari",
      },
      {
        id: 10,
        nama: "Lemari Buku Minimalis",
        harga: 900000,
        deskripsi: "Lemari buku minimalis dengan rak penyimpanan yang praktis.",
        image: require("../assets/lemari_laci.jpg"),
        kategori: "lemari",
      },
    ],
  },
  {
    kategori: "meja",
    items: [
      {
        id: 2,
        nama: "Meja Makan Minimalis",
        harga: 800000,
        deskripsi: "Meja makan minimalis dengan bahan berkualitas tinggi.",
        image: require("../assets/lemari_laci.jpg"),
        kategori: "meja",
      },
      {
        id: 5,
        nama: "Meja Kerja Modern",
        harga: 1000000,
        deskripsi: "Meja kerja modern dengan desain minimalis.",
        image: require("../assets/lemari_laci.jpg"),
        kategori: "meja",
      },
      {
        id: 8,
        nama: "Meja Belajar Anak",
        harga: 600000,
        deskripsi: "Meja belajar anak dengan warna cerah dan menyenangkan.",
        image: require("../assets/lemari_laci.jpg"),
        kategori: "meja",
      },
    ],
  },
  {
    kategori: "kursi",
    items: [
      {
        id: 3,
        nama: "Kursi Sofa Empuk",
        harga: 600000,
        deskripsi: "Kursi sofa empuk yang nyaman untuk duduk.",
        image: require("../assets/lemari_laci.jpg"),
        kategori: "kursi",
      },
      {
        id: 6,
        nama: "Kursi Santai Bulat",
        harga: 500000,
        deskripsi: "Kursi santai bulat yang cocok untuk ruang tamu.",
        image: require("../assets/lemari_laci.jpg"),
        kategori: "kursi",
      },
      {
        id: 9,
        nama: "Kursi Lipat Portable",
        harga: 350000,
        deskripsi: "Kursi lipat portabel yang mudah dibawa ke mana saja.",
        image: require("../assets/lemari_laci.jpg"),
        kategori: "kursi",
      },
    ],
  },
];

export default items;
